### ISSUE TITLE
about 10.13.4+

### ISSUE THREAD

**Issue by DanielNascimento1978** [RehabMan/OS-X-USB-Inject-All#10]
Hey, Rehab, we need edit kexts and use com.apple.driver.usb.AppleUSBXHCI instead com.apple.driver.usb.AppleUSBXHCIPCI? and AppleUSBXHCI instead AppleUSBXHCIPCI.

Thx!
Keep up the good work!

**Comment by RehabMan** [comment]
No idea what you're asking...
USBInjectAll guide:
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/

**Comment by danielnmaldonado** [comment]
after 10.13.4 apple change AppleUSBXHCIPCI to AppleUSBXHCI and your kexts stay in AppleUSBXHCIPCI, dont need change?
![2018-05-03 as 14 58 04](https://user-images.githubusercontent.com/38929388/39594308-b359cf3a-4ee2-11e8-98ee-e557195f9f35.png)
![2018-05-03 as 14 58 35](https://user-images.githubusercontent.com/38929388/39594311-b72befda-4ee2-11e8-9542-2924e145f6fa.png)

**Comment by RehabMan** [comment]
The two AppleUSBXHCIPCI vs. AppleUSBXHCI you mention are unrelated.
USBInjectAll.kext is working just fine in 10.13.4.
