### ISSUE TITLE
Fix for 10.13.5

### ISSUE THREAD

**Issue by lenguyenthedat** [RehabMan/OS-X-USB-Inject-All#12]
Hi there, it seems like this does not work for 10.13.5 yet, can anyone verify?
I'm using MSI Z270i mobo.

**Comment by athlonreg** [comment]
@lenguyenthedat Hi guys, USB port limit patch in 13.5 is similar one, but you will need to  delete the MatchOS option, here

```
Name: com.apple.driver.usb.AppleUSBXHCI
Find: 837D940F 0F839704
Replace: 837D941A 0F839704
Comment: change 15 port limit to 26 in XHCI kext for 10.13.4,10.13.5
```

And this is a disable port limit 
```
Name: com.apple.driver.usb.AppleUSBXHCI
Find: 837D940F 0F839704 0000
Replace: 837D940F 90909090 9090
Comment: disable port limit in XHCI kext for 10.13.4,10.13.5
```

**Comment by lenguyenthedat** [comment]
Correct, I just verified that it works! Should I create a PR too?

**Comment by athlonreg** [comment]
No, the patch data is similar with 13.4, and it already exists in config_patches, we need only to delete the MatchOS option to make it works´◡`

**Comment by lenguyenthedat** [comment]
Got it, thanks man!
