### ISSUE TITLE
Overriding the  IOUSBHostFamily.kext/Contents/Info.plist failed

### ISSUE THREAD

**Issue by Xc2333** [RehabMan/OS-X-USB-Inject-All#13]
Hi,Rehabman,i follow your guide "USB power property injection for Sierra (and later)" 
I have laptop that 10.13.5 installed , using SMBIOS MacBook Pro 11,3 which in the info.plist ,So I just  rename the EC0->EC, then  the AppleBusPowerControllerUSB loaded as expect. But I want to overriding the values ,so I create a SSDT-UIAC like this 
<img width="902" alt="06ff9254a999ad615ad47e7aef2e63f8" src="https://user-images.githubusercontent.com/35050861/42690533-1e2477f8-86d7-11e8-9ca2-714aa826b1ab.png">
The port limit was fine, but the values don't  change at all,look the pic 
<img width="1116" alt="71b00928cb7cf3527d15ad4863ed24bc" src="https://user-images.githubusercontent.com/35050861/42690609-7313d2e0-86d7-11e8-84a3-6cf2d24b819c.png">
I don't know what was happend,may i miss something?

**Comment by RehabMan** [comment]
Use the forums so you can upload complete problem reporting files.
