### ISSUE TITLE
v0.6.9 reset first boot on macOS 10.13.6

### ISSUE THREAD

**Issue by Matgen84** [RehabMan/OS-X-USB-Inject-All#16]
Hi

I use v0.6.7 with custom SSDT: all works fine. 

I install v0.6.9 yesterday in /EFI/Clover/KEXTS/10.13. My system reboots alone, at first startup, when I run macOS High Sierra.

Any idea? Please 

Mobo: Asus P8z77-v Pro

**Comment by RehabMan** [comment]
Use the forums for troubleshooting, not here.
