### ISSUE TITLE
not working with B360 chipset

### ISSUE THREAD

**Issue by BJY1991** [RehabMan/OS-X-USB-Inject-All#17]
macOS Mojave 10.14.1 has native support device id 0xa36d8086 in AppleIntelcnlusbxhci
I have installed USBInjectAll.kext in /Library/Extensions also apply clover kext patch
but can't get usb3.1 gen2 and usb3.1 work with 10Gbps or 5Gbps 
they only can work with 480mbps 
here is my ioreg
[B360M-PRO4.zip](https://github.com/RehabMan/OS-X-USB-Inject-All/files/2533424/B360M-PRO4.zip)

**Comment by RehabMan** [comment]
Your USB configuration is wrong.
Must code SSDT-UIAC.aml to stay within 15-port limit.
Read here:
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/
