### ISSUE TITLE
use this kext, Bluetooth and camera work,but sleep and shutdown error

### ISSUE THREAD

**Issue by liuxu623** [RehabMan/OS-X-USB-Inject-All#3]
My laptop is MSI GT72S 6QF-065CN

100-series chipset (8086:a12f): 14-USB2 ports HS01-HS14, 10-USB3 ports SS01-SS10, plus USR1/USR2) XHC

System log

kernel[0]: 000786.091778 IOUSBHostHIDDevice@14700000,0: IOUSBHostHIDDevice::interruptRetry: resetting device due to IO failures
kernel[0]: 000786.162450 IOUSBHostDevice@14700000: IOUSBHostDevice::getDescriptorGated: compliance violation: USB 2.0 9.3.5: device returned more than wLength data
kernel[0]: 000786.473072 MSI EPF USB@14700000: IOUSBHostDevice::setConfigurationGated: compliance violation: failed to enable remote wake

**Comment by liuxu623** [comment]
I chang DSDT instead of use this kext,I have no problem now,thank you

**Comment by arutkowski00** [comment]
@Irving23 I have the same issue, can you tell me what have you done in DSDT?

**Comment by RehabMan** [comment]
http://www.tonymacx86.com/el-capitan-laptop-support/173616-guide-10-11-usb-changes-solutions.html
