### ISSUE TITLE
restart when shutdown injected usb device in not intel host chip

### ISSUE THREAD

**Issue by bukhakin13** [RehabMan/OS-X-USB-Inject-All#4]
restart when shutdown injected with usb device in not intel host chip
fresco fl1100, asmedia usb3.1 
what I have to do?
I use asus z270-a

**Comment by RehabMan** [comment]
USBInjectAll.kext has nothing to do with non-Intel xHCI.
FL1100 is supported natively.
AsMedia not supported (generally disabled).
