### ISSUE TITLE
imac18,3 sysdef doesn't work

### ISSUE THREAD

**Issue by xelanaiznac** [RehabMan/OS-X-USB-Inject-All#6]
hi rehabman.
I tried your latest kext 0.6.1 with imac18,3 sysdef (because I have 7700k) and I found out that usb injection is not working.
I saw that into info.plist you have added imac18,1 but not iMac 18,3 (most common I think due to 7700k choice)
could you please fix that? thank you

edit: everything working using imac17,1 for example, so i'm sure it's up to imac18,3 the issue

**Comment by RehabMan** [comment]
Added.
