### ISSUE TITLE
no usb3 with Asus x99-a/usb 3.1 bios 3701

### ISSUE THREAD

**Issue by grandosegood** [RehabMan/OS-X-USB-Inject-All#7]
hello there,

I installed usbinjectall and the xcci-x99 kext, as well as adding the port limit patch for 10.12.6 in clover. however, I still don't get usb. I have the controller set to 'auto' and ehci handoff enabled
 and xhci handoff enabled. what else could be causing the issue?>

**Comment by RehabMan** [comment]
Use the forums.
See guide here:
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/
