### ISSUE TITLE
Translation is wrong please guide

### ISSUE THREAD

**Issue by webhappyboy070** [RehabMan/OS-X-USB-Inject-All#9]
error: There is no SDK with the name or path '/Users/zhanghongmin/Downloads/OS-X-USB-Inject-All-master/macosx10.11'

**Comment by RehabMan** [comment]
You have to add the 10.11 SDK to your copy of Xcode.
SDKs are at: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/

I have all such SDKs at /Applications/LegacySDKs, then use a script to setup aliases:
```
#!/bin/bash

osxplatform=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
sdkrepo=$osxplatform/Developer/SDKs/
infoplist=$osxplatform/Info.plist

for sdk in /Applications/LegacySDKs/*.sdk; do
   sudo ln -s $sdk $sdkrepo`basename $sdk`
done
ls -l $sdkrepo

sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.6" $infoplist
```

**Comment by webhappyboy070** [comment]
Do not know how to finish the order

**Comment by RehabMan** [comment]
> Do not know how to finish the order

No idea what you mean by that.

**Comment by webhappyboy070** [comment]
Can I record a video?

**Comment by RehabMan** [comment]
What does "record a video" have to do with SDK?

**Comment by webhappyboy070** [comment]
YES! thank you
